### ISSUE TITLE
Feature request - composable swarms

### ISSUE THREAD

**Issue by Lampei** [parruda/swarm#11]
Really liking what you've done so far (and have only just started drinking the kool aid myself) and this is sparking off *so* many crazy thoughts in my head.

Was just wondering if having something like layered teams might be something for a future feature.

e.g. Rather than having to configure separate YAML for larger and larger teams do something like this similar to real world structure.

Have a "dev" team, and "qa" team, etc yaml files
Then these could implement a "front end ui dev team" and "back end dev team"
The QA team could be "playwright team" and "postman team"

These teams have roles and agents on them with what they perform and are contained in separate yaml files

The configured top level yaml files could then just be things like "Admin area" or "payment API" etc, that uses specific Claude teams.

And you could layer the lower yamls however they want below a parent yaml -> parent yaml -> parent yaml...
So for a "project" you may not need front end agents, so you only implement the backend dev team and postman teams.  You'd still have a PM over the project and a "lead" for each team that maybe coordinates upwards and sideways between teams (think dev and QA) and reviews the code developed by his/her team and PM (as we also see in the real world) who could check with QA team to see if all scenarios.

And as each team is self contained, the circular dependency check would be null and void between the external files as you would have top nodes pointing up to the calling parent.

Just some thoughts on code/yaml reuse and a way for me to not have hundreds of unmaintainable config files along with the communication structure that I would hope the agent teams would be doing anyway.

**Comment by parruda** [comment]
I think this is a great idea and very aligned with how I would like to use this as well!
Let's brainstorm it!

What if we had a new key inside `swarm` in addition to instances: teams, where we could point at other swarm yaml files?

**Comment by Lampei** [comment]
Sounds great!  But what's crazy when I was thinking about it is...that `teams` node may be all that you end up needing with the way you already have it structured and created :)

So for communication -> an instance or a team would only "know" about what is in that yaml.  So perhaps a dev team would only know about the UI team, but would not know about the internals of that team (and should not care either).  So a node with a "team" can communicate out, but the communication can only be done within that team, and externally only with the "main" agent probably.

There may need to be some checks for circular references in case a "child team" also references a team used further up the chain?!?  Maybe?!?

And maybe there should be a description and prompt inside a "team" now so that it can define what the entire team should be used for when being referenced by the parent?

Also allowed tools defined at the top for a team, then can further limit for an instance or maybe too much?

These may all be things to iterate on also :)

But out of the gate -> definitely like the "teams" node with a yaml file + a check for circular references.

```
project_owner
      description: "Project Owner coordinating providing coordination between team efforts for a project"
      directory: .
      model: opus
      connections: [architect, backend_dev_team, backend_qa_team]
      prompt: "You are the project owner coordinating between different team efforts for a project"
      allowed_tools: [Read, Edit, WebSearch]

architect:
      description: "System architect coordinating between service teams"
      directory: .
      model: opus
      connections: [backend_dev_team]
      prompt: "You are the system architect coordinating between different service teams"
      allowed_tools: [Read, Edit, WebSearch]

backend_dev_team:
      team: backend_dev_team.yaml
      directory: .
      connections: [backend_qa_team]

backend_qa_team:
      team: backend_qa_team.yaml
      directory: .
```
