### ISSUE TITLE
Error when a model no longer exists

### ISSUE THREAD

**Issue by dblock** [parruda/swarm#27]
```yaml
version: 1
swarm:
  name: "Ruby Upgrade Swarm"
  main: lead_developer
  before:
    - "echo 'Getting started ...'"
  instances:
    lead_developer:
      description: "Lead developer who coordinates Ruby upgrades in Slack bots."
      directory: ..
      model: haiku
      allowed_tools:
        - Bash
      prompt: |
        You are the lead developer coordinating the team.
        List all the directories in the current directory.
```

The `haiku` model above was removed, but swarm doesn't mind.
